import type { Metadata } from "next";
import { Montserrat, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="author" content="GOC Legal" />
        <meta name="theme-color" content="#0b3d91" />

        {/*  Favicon  */}
        <link rel="icon" href="https://res.cloudinary.com/dre1b2zmh/image/upload/v1705945101/goclegal/favicon-logo.png" type="image/png" />

        {/*  SEO Title & Description  */}
        <title>GOC Legal — Oakland Personal Injury & Auto Accident Lawyer</title>
        <meta name="robots" content="index,follow" />
        <meta name="description" content="GOC Legal is an experienced personal injury and auto accident law firm in Oakland, CA. No upfront fees, maximum compensation, and free consultations. Call us today." />
        <meta name="keywords" content="Personal Injury Lawyer Oakland, Oakland Personal Injury Attorney, Auto Accident Lawyer Oakland, Best Injury Lawyer Oakland, Oakland Injury Attorney" />

        {/*  Open Graph  */}
        <meta property="og:title" content="GOC Legal — Oakland Personal Injury & Auto Accident Lawyer" />
        <meta property="og:site_name" content="GOC Legal" />
        <meta property="og:image" content="https://res.cloudinary.com/dre1b2zmh/image/upload/v1705782311/goclegal/sfcitybgdesktop.webp" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.goclegal.com/" />
        <meta property="og:description" content="GOC Legal, led by Oakland personal injury lawyer Greg O’Connell, represents victims of car accidents, truck crashes, slip and fall injuries, and wrongful death. Free consultation available." />

        {/*  Twitter Card  */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="GOC Legal — Oakland Personal Injury & Auto Accident Lawyer" />
        <meta name="twitter:description" content="GOC Legal provides expert personal injury and auto accident legal services in Oakland, CA. No upfront fees and maximum compensation." />
        <meta name="twitter:image" content="https://res.cloudinary.com/dre1b2zmh/image/upload/v1705782311/goclegal/sfcitybgdesktop.webp" />

        {/*  Canonical  */}
        <link rel="canonical" href="https://www.goclegal.com/" />
        {/* <link href="" rel="publisher" /> */}

        {/* Google Tag (gtag.js) */}
        <Script
          async
          src={`https://www.googletagmanager.com/gtag/js?id=AW-17444498530`}
        />
        <Script id="google-analytics">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-17444498530');
          `}
        </Script>
        {/* Live Chat Script  */}
        <Script id="live-chat" src="https://app.livechatai.com/embed.js" data-id="cmg7bwm430003l404hl3ixvxf" async defer></Script>
      </head>
      <body
        className={`${montserrat.variable} ${cormorantGaramond.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
