name: Cron Jobs

on:
  schedule:
    - cron: "0 16 * * 1" # Weekly blog → Monday 9:00 AM PST
    - cron: "0 17 * * 1" # Weekly ad → Monday 10:00 AM PST
    - cron: "0 15 * * 1" # Weekly Google Ads Ajustiments → Monday 8:00 AM PST
    - cron: "0 16 */2 * *" # Google Ads Optimization → Every 2 days @ 9:00 AM PST

  workflow_dispatch:
    inputs:
      job:
        description: "Run a specific job manually"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - blog
          - ad
          - setup
          - optimize
          - adjust

jobs:
  run-crons:
    runs-on: ubuntu-latest
    
    env: ${{ secrets }}

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      # ----------------------------
      # CRON TASKS
      # ----------------------------

      - name: Weekly blog
        if: github.event.schedule == '0 16 * * 1' || github.event.inputs.job == 'blog' || github.event.inputs.job == 'all'
        run: npx tsx scripts/weeklyBlog.ts

      - name: Weekly ad
        if: github.event.schedule == '0 17 * * 1' || github.event.inputs.job == 'ad' || github.event.inputs.job == 'all'
        run: npx tsx scripts/weeklyAd.ts

      - name: Weekly Google Ads tune
        if: github.event.schedule == '0 15 * * 1' || github.event.inputs.job == 'adjust' || github.event.inputs.job == 'all'
        run: npx tsx scripts/googleAds/adjust.ts
      
      - name: Google Ads Setup (one-time)
        if: github.event.inputs.job == 'setup'
        run: npx tsx scripts/googleAds/setup.ts

      - name: Google Ads
        if: github.event.schedule == '0 16 */2 * *' || github.event.inputs.job == 'optimize' || github.event.inputs.job == 'all'
        run: npx tsx scripts/googleAds/optimize.ts